# Book
<img width="827" alt="스크린샷 2022-02-04 오전 12 38 52" src="https://user-images.githubusercontent.com/86057607/152375508-53ef351c-c1f7-4b8e-9fe7-cf1d4896faf8.png">
try블록에는 예외가 발생할 수 있는 코드가 위치합니다.

try 블록의 코드가 예외없이 정상 실행되면 catch블록의 코드는 실행되지 않습니다.</br>
하지만 try 블록의 코드에서 예외가 발생하면 즉시 실행을 멈추고 catch 블록으로 이동하여 예외처리 코드를 실행합니다.
